### ISSUE TITLE
How to get job's "custom" data in the worker? 

### ISSUE THREAD

**Issue by nne998** [ghilesmeddour/faktory_worker_python#15]
How to get job's "custom" data in the worker? 

simple producer code :
```python
with Client() as client:
            producer = Producer(client=client)
            job_1 = Job(
                jobtype="echo", args=["test"], queue="default", custom={"hello": "world"}
            )
            ret = producer.push(job_1)
       

```

**Comment by ghilesmeddour** [comment]
Hi @nne998,

In the current implementation, it is not possible to access `custom` data via `Consumer` interface. To be able to do this, the code would have to be modified [here](https://github.com/ghilesmeddour/faktory_worker_python/blob/main/src/pyfaktory/consumer.py#L207). Can you tell me more about your needs?
