### ISSUE TITLE
Proposal for a more featureful Job class

### ISSUE THREAD

**Issue by rgarver** [ghilesmeddour/faktory_worker_python#4]
Currently we register our `Callable` with a name for Faktory to invoke. We use the optional `custom` field to pass additional data between our services. Currently this additional job context is inaccessible from the `Callable` since only the args are passed along.

My proposal is to introduce a `pyfaktory.Job` base class as an alternative job handler type. When `pyfaktory.Consumer` detects that the handler is a subclass of this Job class then we will instantiate the class with the raw job dict and then invoke a `perform` instance method with the provided `args`. The `Job` base class would just need to unmarshal the provided dict in to appropriate instance variables on `__init__` and define a `perform(self, *args)` raising a `NotImplementedError` for type checking.

A longer term benefit of this change is that it provides an location to hang before/after hooks from if we decided to add support for lifecycle methods.

I'll pull together a PR for this in a little bit.

**Comment by ghilesmeddour** [comment]
Thanks for the suggestion, but I'm still having trouble grasping the real benefit. I'm waiting for the PR to understand better. Please, include an example of a use case.

**Comment by rgarver** [comment]
@ghilesmeddour I'm going to pick this back up in a week or two. I have a concept of how this could work. This is based on some hacking we did in our use of faktory.

**Comment by ghilesmeddour** [comment]
@rgarver Perfect! Can't wait to see it!
