### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by rgarver** [ghilesmeddour/faktory_worker_python#5]
@ghilesmeddour How do you feel about getting this project under a formal OSS license? My recommendation would be one of MIT, Apache 2, or MPL 2, but I'm open to discuss. My employer is interested in investing more fully in this project, but one concern is the lack of explicit licensing. I'm happy to throw together a PR based on your feedback to this issue.

**Comment by ghilesmeddour** [comment]
It was an oversight ;) Let's go for MIT license. Yes, do it please. Thanks.
