### ISSUE TITLE
Auto-reload consumer

### ISSUE THREAD

**Issue by jesseduffield** [ghilesmeddour/faktory_worker_python#9]
When developing locally, it's useful to have a consumer process running continuously, but for it to auto-reload whenever code changes.

We don't need to add that behaviour to this package but I'm wondering how I could go about it. E.g. if I have my own code for watching the filesystem, and I send an interrupt to the consumer process, does it wait for any currently running jobs to finish first, or does it just kill them in-flight?

Thanks

**Comment by ghilesmeddour** [comment]
Auto-reload in development mode is a good idea. I currently don't know how to develop it in the package, but I might look into it in the future or merge a PR in that direction.

For the shutdown behaviour, [Consumer has a grace period between the beginning of a shutdown and its end](https://github.com/ghilesmeddour/faktory_worker_python/blob/639b3e663f4e086d3fb091a5ebb4c3cc29f8e247/src/pyfaktory/consumer.py#L49). By default, it's set to 25 seconds.
